LucaBrivio183/deliveboo-backend

- database/migrations/2023_06_14_143221_create_restaurants_table.php
- database/seeders/RestaurantSeeder.php
- database/seeders/UserSeeder.php
Aggiunto seeder per cinque utenti
> feat restaurant migration/seeder + user seeder

- database/seeders/ProductSeeder.php
Ho creato un seeder basilare per i prodotti
> product seeder

- app/Http/Controllers/Admin/DashboardController.php
- app/Http/Controllers/Admin/RestaurantController.php
- app/Models/Restaurant.php
- app/Models/User.php
- resources/views/admin/restaurants/index.blade.php
- resources/views/admin/restaurants/show.blade.php
- resources/views/dashboard.blade.php
- routes/web.php
> feat: user-restaurant relation

- resources/views/admin/products/show.blade.php
corretto errore in show di products
> fix: products.show

- app/Http/Controllers/Admin/RestaurantController.php
- app/Models/Restaurant.php
- app/Models/Typology.php
- database/migrations/2023_06_15_153705_create_restaurant_typology_table.php
- database/seeders/TypologySeeder.php
- resources/views/admin/restaurants/create.blade.php
- resources/views/admin/restaurants/edit.blade.php
> feat: restaurants typologies relation

- app/Http/Controllers/Admin/RestaurantController.php
- resources/js/app.js
- resources/js/functions/image_preview.js
- resources/scss/_partials/_form.scss
- resources/scss/app.scss
- resources/views/admin/restaurants/create.blade.php
- resources/views/admin/restaurants/edit.blade.php
> restaurants create/edit minor feats and fixes

- app/Http/Controllers/Admin/RestaurantController.php
- app/Http/Requests/StoreRestaurantRequest.php
- app/Http/Requests/UpdateRestaurantRequest.php
- resources/views/admin/restaurants/create.blade.php
- resources/views/admin/restaurants/edit.blade.php
I ristoranti possono ora scegliere fino a un massimo di tre tipologie. Cambiata grafica delle tipologie nel create e edit dei ristoranti.
closes #38
> feat: max typologies per restaurant

- resources/scss/_partials/_show.scss
- resources/scss/app.scss
- resources/views/admin/restaurants/show.blade.php
Tradotto show in italiano, aggiunto commenti e condizioni per stampare i dati.
closes #42
> feat:restaurant-show-translation

- app/Models/Order.php
- app/Models/Product.php
- app/Models/Restaurant.php
- app/Models/Typology.php
- app/Models/User.php
- database/migrations/2023_06_15_083506_create_orders_table.php
- database/migrations/2023_06_19_213901_create_order_product_table.php
Migration per la tabella degli ordini e per la tabella pivot collegante gli ordini e i prodotti.
closes #44
> feat:orders/order_table-migrations

- database/migrations/2023_06_15_083506_create_orders_table.php
Aggiunto total_price (decimal(5, 2)) alla tabella orders
closes #46
> feat:orders_table -> total_price

- app/Http/Controllers/Api/TypologyController.php
- routes/api.php
Recupera le tutte e solo le tipologie associate ad almeno un ristorante, route collegata.
closes #55
> feat: homepage typologies api

- routes/api.php
> fix: api controller namespace

- app/Http/Controllers/Admin/RestaurantController.php
- resources/views/layouts/app.blade.php
- resources/views/welcome.blade.php
- routes/web.php
Ho creato due pagine differenti per gli utenti con e senza ristorante. Ho inoltre rimosso il collegamento alla dashboard per gli utenti che non ne hanno una.
> 61 edit welcome view

- resources/views/auth/register.blade.php
Validazione password client side
#64
> feat: registration password validation

- resources/views/auth/login.blade.php
- resources/views/auth/register.blade.php
> feat: login password validation

- app/Http/Controllers/Admin/DashboardController.php
- app/Http/Controllers/Admin/RestaurantController.php
Se un utente registrato senza ristorante prova ad andare sulla dashboard o sulla pagina del ristorante, viene reindirizzato alla welcome.
closes #68
> user without restaurants redirected to welcome

- app/Models/Restaurant.php
- app/Models/RestaurantTypology.php
- database/seeders/DatabaseSeeder.php
- database/seeders/RestaurantTypologySeeder.php
- resources/views/auth/register.blade.php
> feat:restaurant_typology_seeder

- app/Http/Requests/StoreProductRequest.php
- app/Http/Requests/UpdateProductRequest.php
- resources/views/admin/products/create.blade.php
- resources/views/admin/products/edit.blade.php
- resources/views/admin/products/index.blade.php
Ho tolto la descrizione dei prodotti dall'index, ho limitato il loro prezzo ad un massimo di 99 e ho aggiunto un'icona per indicare se un prodotto è visibile o meno per il cliente
> 73 edit products info

- app/Http/Controllers/Api/RestaurantController.php
> Feat: homepage filtered api

- app/Http/Requests/StoreProductRequest.php
- app/Http/Requests/UpdateProductRequest.php
- database/migrations/2023_06_15_105725_add_category_id_foreign_key_to_products_table.php
- database/seeders/ProductSeeder.php
- resources/views/admin/products/create.blade.php
- resources/views/admin/products/edit.blade.php
- resources/views/admin/products/show.blade.php
Commentate le linee riguardanti le categorie in create, edit e show products. Commentata la validazione delle categorie dai store e update product request. Commentata la colonna della category_id nella tabella products. Commentato il seeder della category_id nel Product Seeder.
closes #72
> fix: resolve categories problem

- app/Http/Controllers/Admin/DashboardController.php
- resources/scss/_partials/_dashboard.scss
- resources/views/admin/restaurants/index.blade.php
- resources/views/dashboard.blade.php
> Feat: dashboard enhancement

- database/migrations/2023_06_15_083247_create_typologies_table.php
- database/seeders/RestaurantTypologySeeder.php
- database/seeders/TypologySeeder.php
Aggiunto immagini alla migration delle tipologie, aggiunto un link per immagine al seeder
> hotfix: typology migration and seeder

- app/Http/Controllers/Admin/DashboardController.php
- app/Http/Controllers/Admin/ProductController.php
- resources/js/functions/image_preview.js
- resources/scss/_partials/_dashboard.scss
- resources/scss/global.scss
- resources/views/admin/products/edit.blade.php
- resources/views/admin/products/show.blade.php
- resources/views/admin/restaurants/edit.blade.php
- resources/views/dashboard.blade.php
Risistemato la dashboard, grandezza immagini e salvataggio e update delle immagini dei prodotti
> fix: backoffice and images rework

- app/Http/Controllers/Admin/StatsController.php
- package-lock.json
- package.json
- resources/js/app.js
- resources/js/functions/chart.js
- resources/views/admin/orders/stats.blade.php
- routes/web.php
ho inserito il primo grafico per le statistiche, gestito da un controller che invia gli ordini del ristorante
> 100 add stats

- database/seeders/DatabaseSeeder.php
- database/seeders/OrderSeeder.php
Seeder per ordini e order_product di un ristorante
> feat: orders and order_product seeder

- app/Http/Controllers/Admin/StatsController.php
- resources/js/functions/chart.js
- resources/views/admin/orders/stats.blade.php
ho aggiunto le statistiche annuali di ordini ricevuti e fatturato
> Add more stats
